function CodePage(cp){
	this.id=cp.id;
	this.name=cp.name;
	this.friendlyName=cp.friendlyName;
}
CodePage.prototype.decodeToUTF8=function(text){
	return decodeFrom(this.id, text);
}

function CodePages(codePages){
	this.init(codePages);
};
CodePages.prototype.byId={};//doesn't work by unknown reason
CodePages.prototype.byName={};
CodePages.prototype.list=[];
CodePages.prototype.init=function(codePages){
	this.byId={};
	this.byName={};
	this.list=codePages.map(function(cp){return new CodePage(cp);});
	for(var i;i<this.list.length;i++){
		this.byId[cp.id]=this.list[i];
		this.byName[cp.name]=this.list[i];
	}
}
CodePages.prototype.getCurDocCP=function(){
	return this.byId[Editor.currentView.codepage];
};

var codePages = new CodePages([ 
	{id:37,     name:"IBM037",                  friendlyName:"IBM EBCDIC (US-Canada)"},
	{id:437,    name:"IBM437",                  friendlyName:"OEM United States"},
	{id:500,    name:"IBM500",                  friendlyName:"IBM EBCDIC (International)"},
	{id:708,    name:"ASMO-708",                friendlyName:"Arabic (ASMO 708)"},
	{id:720,    name:"DOS-720",                 friendlyName:"Arabic (DOS)"},
	{id:737,    name:"ibm737",                  friendlyName:"Greek (DOS)"},
	{id:775,    name:"ibm775",                  friendlyName:"Baltic (DOS)"},
	{id:850,    name:"ibm850",                  friendlyName:"Western European (DOS)"},
	{id:852,    name:"ibm852",                  friendlyName:"Central European (DOS)"},
	{id:855,    name:"IBM855",                  friendlyName:"OEM Cyrillic"},
	{id:857,    name:"ibm857",                  friendlyName:"Turkish (DOS)"},
	{id:858,    name:"IBM00858",                friendlyName:"OEM Multilingual Latin I"},
	{id:860,    name:"IBM860",                  friendlyName:"Portuguese (DOS)"},
	{id:861,    name:"ibm861",                  friendlyName:"Icelandic (DOS)"},
	{id:862,    name:"DOS-862",                 friendlyName:"Hebrew (DOS)"},
	{id:863,    name:"IBM863",                  friendlyName:"French Canadian (DOS)"},
	{id:864,    name:"IBM864",                  friendlyName:"Arabic (864)"},
	{id:865,    name:"IBM865",                  friendlyName:"Nordic (DOS)"},
	{id:866,    name:"cp866",                   friendlyName:"Cyrillic (DOS)"},
	{id:869,    name:"ibm869",                  friendlyName:"Greek, Modern (DOS)"},
	{id:870,    name:"IBM870",                  friendlyName:"IBM EBCDIC (Multilingual Latin-2)"},
	{id:874,    name:"windows-874",             friendlyName:"Thai (Windows)"},
	{id:875,    name:"cp875",                   friendlyName:"IBM EBCDIC (Greek Modern)"},
	{id:932,    name:"shift_jis",               friendlyName:"Japanese (Shift-JIS)"},
	{id:936,    name:"gb2312",                  friendlyName:"Chinese Simplified (GB2312)"},
	{id:949,    name:"ks_c_5601-1987",          friendlyName:"Korean"},
	{id:950,    name:"big5",                    friendlyName:"Chinese Traditional (Big5)"},
	{id:1026,   name:"IBM1026",                 friendlyName:"IBM EBCDIC (Turkish Latin-5)"},
	{id:1047,   name:"IBM01047",                friendlyName:"IBM Latin-1"},
	{id:1140,   name:"IBM01140",                friendlyName:"IBM EBCDIC (US-Canada-Euro)"},
	{id:1141,   name:"IBM01141",                friendlyName:"IBM EBCDIC (Germany-Euro)"},
	{id:1142,   name:"IBM01142",                friendlyName:"IBM EBCDIC (Denmark-Norway-Euro)"},
	{id:1143,   name:"IBM01143",                friendlyName:"IBM EBCDIC (Finland-Sweden-Euro)"},
	{id:1144,   name:"IBM01144",                friendlyName:"IBM EBCDIC (Italy-Euro)"},
	{id:1145,   name:"IBM01145",                friendlyName:"IBM EBCDIC (Spain-Euro)"},
	{id:1146,   name:"IBM01146",                friendlyName:"IBM EBCDIC (UK-Euro)"},
	{id:1147,   name:"IBM01147",                friendlyName:"IBM EBCDIC (France-Euro)"},
	{id:1148,   name:"IBM01148",                friendlyName:"IBM EBCDIC (International-Euro)"},
	{id:1149,   name:"IBM01149",                friendlyName:"IBM EBCDIC (Icelandic-Euro)"},
	{id:1200,   name:"utf-16",                  friendlyName:"Unicode"},
	{id:1201,   name:"unicodeFFFE",             friendlyName:"Unicode (Big-Endian)"},
	{id:1250,   name:"windows-1250",            friendlyName:"Central European (Windows)"},
	{id:1251,   name:"windows-1251",            friendlyName:"Cyrillic (Windows)"},
	{id:1252,   name:"Windows-1252",            friendlyName:"Western European (Windows)"},
	{id:1253,   name:"windows-1253",            friendlyName:"Greek (Windows)"},
	{id:1254,   name:"windows-1254",            friendlyName:"Turkish (Windows)"},
	{id:1255,   name:"windows-1255",            friendlyName:"Hebrew (Windows)"},
	{id:1256,   name:"windows-1256",            friendlyName:"Arabic (Windows)"},
	{id:1257,   name:"windows-1257",            friendlyName:"Baltic (Windows)"},
	{id:1258,   name:"windows-1258",            friendlyName:"Vietnamese (Windows)"},
	{id:1361,   name:"Johab",                   friendlyName:"Korean (Johab)"},
	{id:10000,  name:"macintosh",               friendlyName:"Western European (Mac)"},
	{id:10001,  name:"x-mac-japanese",          friendlyName:"Japanese (Mac)"},
	{id:10002,  name:"x-mac-chinesetrad",       friendlyName:"Chinese Traditional (Mac)"},
	{id:10003,  name:"x-mac-korean",            friendlyName:"Korean (Mac)"},
	{id:10004,  name:"x-mac-arabic",            friendlyName:"Arabic (Mac)"},
	{id:10005,  name:"x-mac-hebrew",            friendlyName:"Hebrew (Mac)"},
	{id:10006,  name:"x-mac-greek",             friendlyName:"Greek (Mac)"},
	{id:10007,  name:"x-mac-cyrillic",          friendlyName:"Cyrillic (Mac)"},
	{id:10008,  name:"x-mac-chinesesimp",       friendlyName:"Chinese Simplified (Mac)"},
	{id:10010,  name:"x-mac-romanian",          friendlyName:"Romanian (Mac)"},
	{id:10017,  name:"x-mac-ukrainian",         friendlyName:"Ukrainian (Mac)"},
	{id:10021,  name:"x-mac-thai",              friendlyName:"Thai (Mac)"},
	{id:10029,  name:"x-mac-ce",                friendlyName:"Central European (Mac)"},
	{id:10079,  name:"x-mac-icelandic",         friendlyName:"Icelandic (Mac)"},
	{id:10081,  name:"x-mac-turkish",           friendlyName:"Turkish (Mac)"},
	{id:10082,  name:"x-mac-croatian",          friendlyName:"Croatian (Mac)"},
	{id:20000,  name:"x-Chinese-CNS",           friendlyName:"Chinese Traditional (CNS)"},
	{id:20001,  name:"x-cp20001",               friendlyName:"TCA Taiwan"},
	{id:20002,  name:"x-Chinese-Eten",          friendlyName:"Chinese Traditional (Eten)"},
	{id:20003,  name:"x-cp20003",               friendlyName:"IBM5550 Taiwan"},
	{id:20004,  name:"x-cp20004",               friendlyName:"TeleText Taiwan"},
	{id:20005,  name:"x-cp20005",               friendlyName:"Wang Taiwan"},
	{id:20105,  name:"x-IA5",                   friendlyName:"Western European (IA5)"},
	{id:20106,  name:"x-IA5-German",            friendlyName:"German (IA5)"},
	{id:20107,  name:"x-IA5-Swedish",           friendlyName:"Swedish (IA5)"},
	{id:20108,  name:"x-IA5-Norwegian",         friendlyName:"Norwegian (IA5)"},
	{id:20127,  name:"us-ascii",                friendlyName:"US-ASCII"},
	{id:20261,  name:"x-cp20261",               friendlyName:"T.61"},
	{id:20269,  name:"x-cp20269",               friendlyName:"ISO-6937"},
	{id:20273,  name:"IBM273",                  friendlyName:"IBM EBCDIC (Germany)"},
	{id:20277,  name:"IBM277",                  friendlyName:"IBM EBCDIC (Denmark-Norway)"},
	{id:20278,  name:"IBM278",                  friendlyName:"IBM EBCDIC (Finland-Sweden)"},
	{id:20280,  name:"IBM280",                  friendlyName:"IBM EBCDIC (Italy)"},
	{id:20284,  name:"IBM284",                  friendlyName:"IBM EBCDIC (Spain)"},
	{id:20285,  name:"IBM285",                  friendlyName:"IBM EBCDIC (UK)"},
	{id:20290,  name:"IBM290",                  friendlyName:"IBM EBCDIC (Japanese katakana)"},
	{id:20297,  name:"IBM297",                  friendlyName:"IBM EBCDIC (France)"},
	{id:20420,  name:"IBM420",                  friendlyName:"IBM EBCDIC (Arabic)"},
	{id:20423,  name:"IBM423",                  friendlyName:"IBM EBCDIC (Greek)"},
	{id:20424,  name:"IBM424",                  friendlyName:"IBM EBCDIC (Hebrew)"},
	{id:20833,  name:"x-EBCDIC-KoreanExtended", friendlyName:"IBM EBCDIC (Korean Extended)"},
	{id:20838,  name:"IBM-Thai",                friendlyName:"IBM EBCDIC (Thai)"},
	{id:20866,  name:"koi8-r",                  friendlyName:"Cyrillic (KOI8-R)"},
	{id:20871,  name:"IBM871",                  friendlyName:"IBM EBCDIC (Icelandic)"},
	{id:20880,  name:"IBM880",                  friendlyName:"IBM EBCDIC (Cyrillic Russian)"},
	{id:20905,  name:"IBM905",                  friendlyName:"IBM EBCDIC (Turkish)"},
	{id:20924,  name:"IBM00924",                friendlyName:"IBM Latin-1"},
	{id:20932,  name:"EUC-JP",                  friendlyName:"Japanese (JIS 0208-1990 and 0212-1990)"},
	{id:20936,  name:"x-cp20936",               friendlyName:"Chinese Simplified (GB2312-80)"},
	{id:20949,  name:"x-cp20949",               friendlyName:"Korean Wansung"},
	{id:21025,  name:"cp1025",                  friendlyName:"IBM EBCDIC (Cyrillic Serbian-Bulgarian)"},
	{id:21866,  name:"koi8-u",                  friendlyName:"Cyrillic (KOI8-U)"},
	{id:28591,  name:"iso-8859-1",              friendlyName:"Western European (ISO)"},
	{id:28592,  name:"iso-8859-2",              friendlyName:"Central European (ISO)"},
	{id:28593,  name:"iso-8859-3",              friendlyName:"Latin 3 (ISO)"},
	{id:28594,  name:"iso-8859-4",              friendlyName:"Baltic (ISO)"},
	{id:28595,  name:"iso-8859-5",              friendlyName:"Cyrillic (ISO)"},
	{id:28596,  name:"iso-8859-6",              friendlyName:"Arabic (ISO)"},
	{id:28597,  name:"iso-8859-7",              friendlyName:"Greek (ISO)"},
	{id:28598,  name:"iso-8859-8",              friendlyName:"Hebrew (ISO-Visual)"},
	{id:28599,  name:"iso-8859-9",              friendlyName:"Turkish (ISO)"},
	{id:28603,  name:"iso-8859-13",             friendlyName:"Estonian (ISO)"},
	{id:28605,  name:"iso-8859-15",             friendlyName:"Latin 9 (ISO)"},
	{id:29001,  name:"x-Europa",                friendlyName:"Europa"},
	{id:38598,  name:"iso-8859-8-i",            friendlyName:"Hebrew (ISO-Logical)"},
	{id:50220,  name:"iso-2022-jp",             friendlyName:"Japanese (JIS)"},
	{id:50221,  name:"csISO2022JP",             friendlyName:"Japanese (JIS-Allow 1 byte Kana)"},
	{id:50222,  name:"iso-2022-jp",             friendlyName:"Japanese (JIS-Allow 1 byte Kana - SO/SI)"},
	{id:50225,  name:"iso-2022-kr",             friendlyName:"Korean (ISO)"},
	{id:50227,  name:"x-cp50227",               friendlyName:"Chinese Simplified (ISO-2022)"},
	{id:51932,  name:"euc-jp",                  friendlyName:"Japanese (EUC)"},
	{id:51936,  name:"EUC-CN",                  friendlyName:"Chinese Simplified (EUC)"},
	{id:51949,  name:"euc-kr",                  friendlyName:"Korean (EUC)"},
	{id:52936,  name:"hz-gb-2312",              friendlyName:"Chinese Simplified (HZ)"},
	{id:54936,  name:"GB18030",                 friendlyName:"Chinese Simplified (GB18030)"},
	{id:57002,  name:"x-iscii-de",              friendlyName:"ISCII Devanagari"},
	{id:57003,  name:"x-iscii-be",              friendlyName:"ISCII Bengali"},
	{id:57004,  name:"x-iscii-ta",              friendlyName:"ISCII Tamil"},
	{id:57005,  name:"x-iscii-te",              friendlyName:"ISCII Telugu"},
	{id:57006,  name:"x-iscii-as",              friendlyName:"ISCII Assamese"},
	{id:57007,  name:"x-iscii-or",              friendlyName:"ISCII Oriya"},
	{id:57008,  name:"x-iscii-ka",              friendlyName:"ISCII Kannada"},
	{id:57009,  name:"x-iscii-ma",              friendlyName:"ISCII Malayalam"},
	{id:57010,  name:"x-iscii-gu",              friendlyName:"ISCII Gujarati"},
	{id:57011,  name:"x-iscii-pa",              friendlyName:"ISCII Punjabi"},
	{id:65000,  name:"utf-7",                   friendlyName:"Unicode (UTF-7)"},
	{id:65001,  name:"utf-8",                   friendlyName:"Unicode (UTF-8)"},
	{id:65005,  name:"utf-32",                  friendlyName:"Unicode (UTF-32)"},
	{id:65006,  name:"utf-32BE",                friendlyName:"Unicode (UTF-32 Big-Endian)"}
]);
