/**!
 * https://github.com/es-shims/es5-shim
 * @license es5-shim Copyright 2009-2014 by contributors, MIT License
 * see https://github.com/es-shims/es5-shim/blob/master/LICENSE
 */
(function(){function r(a){if(null==a)throw new TypeError("can't convert "+a+" to object");return Object(a)}function v(){}function A(a){a=+a;a!==a?a=0:0!==a&&a!==1/0&&a!==-(1/0)&&(a=(0<a||-1)*Math.floor(Math.abs(a)));return a}function w(a){var b=typeof a;return null===a||"undefined"===b||"boolean"===b||"number"===b||"string"===b}Function.prototype.bind||(Function.prototype.bind=function(a){var b=this;if("function"!=typeof b)throw new TypeError("Function.prototype.bind called on incompatible "+b);for(var e=
s.call(arguments,1),c=Math.max(0,b.length-e.length),d=[],g=0;g<c;g++)d.push("$"+g);var h=Function("binder","return function("+d.join(",")+"){return binder.apply(this,arguments)}")(function(){if(this instanceof h){var c=b.apply(this,e.concat(s.call(arguments)));return Object(c)===c?c:this}return b.apply(a,e.concat(s.call(arguments)))});b.prototype&&(v.prototype=b.prototype,h.prototype=new v,v.prototype=null);return h});var m=Function.prototype.call,t=Object.prototype,s=Array.prototype.slice,l=m.bind(t.toString),
x=m.bind(t.hasOwnProperty);x(t,"__defineGetter__")&&(m.bind(t.__defineGetter__),m.bind(t.__defineSetter__),m.bind(t.__lookupGetter__),m.bind(t.__lookupSetter__));if(2!=[1,2].splice(0).length){var y=Array.prototype.splice,E=Array.prototype.push,z=Array.prototype.unshift;(function(){function a(a){for(var b=[];a--;)b.unshift(a);return b}var b=[],e;b.splice.bind(b,0,0).apply(null,a(20));b.splice.bind(b,0,0).apply(null,a(26));e=b.length;b.splice(5,0,"XXX");if(e+1==b.length)return!0})()?Array.prototype.splice=
function(a,b){return arguments.length?y.apply(this,[void 0===a?0:a,void 0===b?this.length-a:b].concat(s.call(arguments,2))):[]}:Array.prototype.splice=function(a,b){var e,c=s.call(arguments,2);e=c.length;if(!arguments.length)return[];void 0===a&&(a=0);void 0===b&&(b=this.length-a);if(0<e){if(0>=b){if(a==this.length)return E.apply(this,c),[];if(0==a)return z.apply(this,c),[]}e=s.call(this,a,a+b);c.push.apply(c,s.call(this,a+b,this.length));c.unshift.apply(c,s.call(this,0,a));c.unshift(0,this.length);
y.apply(this,c);return e}return y.call(this,a,b)}}1!=[].unshift(0)&&(z=Array.prototype.unshift,Array.prototype.unshift=function(){z.apply(this,arguments);return this.length});Array.isArray||(Array.isArray=function(a){return"[object Array]"==l(a)});var m=Object("a"),q="a"!=m[0]||!(0 in m),m=function(a){var b=!0;a&&a.call("foo",function(a,c,d){"object"!==typeof d&&(b=!1)});return!!a&&b};Array.prototype.forEach&&m(Array.prototype.forEach)||(Array.prototype.forEach=function(a,b){var e=r(this),c=q&&"[object String]"==
l(this)?this.split(""):e,d=-1,g=c.length>>>0;if("[object Function]"!=l(a))throw new TypeError;for(;++d<g;)d in c&&a.call(b,c[d],d,e)});Array.prototype.map&&m(Array.prototype.map)||(Array.prototype.map=function(a,b){var e=r(this),c=q&&"[object String]"==l(this)?this.split(""):e,d=c.length>>>0,g=Array(d);if("[object Function]"!=l(a))throw new TypeError(a+" is not a function");for(var h=0;h<d;h++)h in c&&(g[h]=a.call(b,c[h],h,e));return g});Array.prototype.filter&&m(Array.prototype.filter)||(Array.prototype.filter=
function(a,b){var e=r(this),c=q&&"[object String]"==l(this)?this.split(""):e,d=c.length>>>0,g=[],h;if("[object Function]"!=l(a))throw new TypeError(a+" is not a function");for(var u=0;u<d;u++)u in c&&(h=c[u],a.call(b,h,u,e)&&g.push(h));return g});Array.prototype.every&&m(Array.prototype.every)||(Array.prototype.every=function(a,b){var e=r(this),c=q&&"[object String]"==l(this)?this.split(""):e,d=c.length>>>0;if("[object Function]"!=l(a))throw new TypeError(a+" is not a function");for(var g=0;g<d;g++)if(g in
c&&!a.call(b,c[g],g,e))return!1;return!0});Array.prototype.some&&m(Array.prototype.some)||(Array.prototype.some=function(a,b){var e=r(this),c=q&&"[object String]"==l(this)?this.split(""):e,d=c.length>>>0;if("[object Function]"!=l(a))throw new TypeError(a+" is not a function");for(var g=0;g<d;g++)if(g in c&&a.call(b,c[g],g,e))return!0;return!1});Array.prototype.reduce||(Array.prototype.reduce=function(a){var b=r(this),e=q&&"[object String]"==l(this)?this.split(""):b,c=e.length>>>0;if("[object Function]"!=
l(a))throw new TypeError(a+" is not a function");if(!c&&1==arguments.length)throw new TypeError("reduce of empty array with no initial value");var d=0,g;if(2<=arguments.length)g=arguments[1];else{do{if(d in e){g=e[d++];break}if(++d>=c)throw new TypeError("reduce of empty array with no initial value");}while(1)}for(;d<c;d++)d in e&&(g=a.call(void 0,g,e[d],d,b));return g});Array.prototype.reduceRight||(Array.prototype.reduceRight=function(a){var b=r(this),e=q&&"[object String]"==l(this)?this.split(""):
b,c=e.length>>>0;if("[object Function]"!=l(a))throw new TypeError(a+" is not a function");if(!c&&1==arguments.length)throw new TypeError("reduceRight of empty array with no initial value");var d,c=c-1;if(2<=arguments.length)d=arguments[1];else{do{if(c in e){d=e[c--];break}if(0>--c)throw new TypeError("reduceRight of empty array with no initial value");}while(1)}if(0>c)return d;do c in this&&(d=a.call(void 0,d,e[c],c,b));while(c--);return d});Array.prototype.indexOf&&-1==[0,1].indexOf(1,2)||(Array.prototype.indexOf=
function(a){var b=q&&"[object String]"==l(this)?this.split(""):r(this),e=b.length>>>0;if(!e)return-1;var c=0;1<arguments.length&&(c=A(arguments[1]));for(c=0<=c?c:Math.max(0,e+c);c<e;c++)if(c in b&&b[c]===a)return c;return-1});Array.prototype.lastIndexOf&&-1==[0,1].lastIndexOf(0,-3)||(Array.prototype.lastIndexOf=function(a){var b=q&&"[object String]"==l(this)?this.split(""):r(this),e=b.length>>>0;if(!e)return-1;var c=e-1;1<arguments.length&&(c=Math.min(c,A(arguments[1])));for(c=0<=c?c:e-Math.abs(c);0<=
c;c--)if(c in b&&a===b[c])return c;return-1});if(!Object.keys){var B=!0,F=function(){}.propertyIsEnumerable("prototype"),C="toString toLocaleString valueOf hasOwnProperty isPrototypeOf propertyIsEnumerable constructor".split(" "),G=C.length,n;for(n in{toString:null})B=!1;Object.keys=function(a){var b="[object Function]"===l(a);if((null===a||"object"!==typeof a)&&!b)throw new TypeError("Object.keys called on a non-object");var e=[],b=F&&b,c;for(c in a)b&&"prototype"===c||!x(a,c)||e.push(c);if(B)for(c=
(c=a.constructor)&&c.prototype===a,b=0;b<G;b++){var d=C[b];c&&"constructor"===d||!x(a,d)||e.push(d)}return e}}Date.prototype.toISOString&&-1!==(new Date(-621987552E5)).toISOString().indexOf("-000001")||(Date.prototype.toISOString=function(){var a,b,e,c;if(!isFinite(this))throw new RangeError("Date.prototype.toISOString called on non-finite value.");c=this.getUTCFullYear();a=this.getUTCMonth();c+=Math.floor(a/12);a=[(a%12+12)%12+1,this.getUTCDate(),this.getUTCHours(),this.getUTCMinutes(),this.getUTCSeconds()];
c=(0>c?"-":9999<c?"+":"")+("00000"+Math.abs(c)).slice(0<=c&&9999>=c?-4:-6);for(b=a.length;b--;)e=a[b],10>e&&(a[b]="0"+e);return c+"-"+a.slice(0,2).join("-")+"T"+a.slice(2).join(":")+"."+("000"+this.getUTCMilliseconds()).slice(-3)+"Z"});n=!1;try{n=Date.prototype.toJSON&&null===(new Date(NaN)).toJSON()&&-1!==(new Date(-621987552E5)).toJSON().indexOf("-000001")&&Date.prototype.toJSON.call({toISOString:function(){return!0}})}catch(K){}n||(Date.prototype.toJSON=function(a){a=Object(this);var b;if(w(a))b=
a;else if(b=a.valueOf,"function"!==typeof b||(b=b.call(a),!w(b)))if(b=a.toString,"function"!==typeof b||(b=b.call(a),!w(b)))throw new TypeError;if("number"===typeof b&&!isFinite(b))return null;b=a.toISOString;if("function"!=typeof b)throw new TypeError("toISOString property is not callable");return b.call(a)});if(!Date.parse||isNaN(Date.parse("2000-01-01T00:00:00.000Z")))Date=function(a){function b(c,e,f,d,g,l,m){var p=arguments.length;return this instanceof a?(p=1==p&&String(c)===c?new a(b.parse(c)):
7<=p?new a(c,e,f,d,g,l,m):6<=p?new a(c,e,f,d,g,l):5<=p?new a(c,e,f,d,g):4<=p?new a(c,e,f,d):3<=p?new a(c,e,f):2<=p?new a(c,e):1<=p?new a(c):new a,p.constructor=b,p):a.apply(this,arguments)}function e(a,c){var b=1<c?1:0;return d[c]+Math.floor((a-1969+b)/4)-Math.floor((a-1901+b)/100)+Math.floor((a-1601+b)/400)+365*(a-1970)}var c=RegExp("^(\\d{4}|[+-]\\d{6})(?:-(\\d{2})(?:-(\\d{2})(?:T(\\d{2}):(\\d{2})(?::(\\d{2})(?:(\\.\\d{1,}))?)?(Z|(?:([-+])(\\d{2}):(\\d{2})))?)?)?)?$"),d=[0,31,59,90,120,151,181,
212,243,273,304,334,365],g;for(g in a)b[g]=a[g];b.now=a.now;b.UTC=a.UTC;b.prototype=a.prototype;b.prototype.constructor=b;b.parse=function(b){var d=c.exec(b);if(d){var f=Number(d[1]),g=Number(d[2]||1)-1,k=Number(d[3]||1)-1,l=Number(d[4]||0),m=Number(d[5]||0),p=Number(d[6]||0),n=Math.floor(1E3*Number(d[7]||0)),r=Boolean(d[4]&&!d[8]),q="-"===d[9]?1:-1,s=Number(d[10]||0),d=Number(d[11]||0);return l<(0<m||0<p||0<n?24:25)&&60>m&&60>p&&1E3>n&&-1<g&&12>g&&24>s&&60>d&&-1<k&&k<e(f,g+1)-e(f,g)&&(f=60*(24*(e(f,
g)+k)+l+s*q),f=1E3*(60*(f+m+d*q)+p)+n,r&&(f=Number(new a(1970,0,1,0,0,0,f))),-864E13<=f&&864E13>=f)?f:NaN}return a.parse.apply(this,arguments)};return b}(Date);Date.now||(Date.now=function(){return(new Date).getTime()});Number.prototype.toFixed&&"0.000"===(8E-5).toFixed(3)&&"0"!==(0.9).toFixed(0)&&"1.25"===(1.255).toFixed(2)&&"1000000000000000128"===(0xde0b6b3a7640080).toFixed(0)||function(){function a(a,b){for(var c=-1;++c<g;)b+=a*h[c],h[c]=b%d,b=Math.floor(b/d)}function b(a){for(var b=g,c=0;0<=
--b;)c+=h[b],h[b]=Math.floor(c/a),c=c%a*d}function e(){for(var a=g,b="";0<=--a;)if(""!==b||0===a||0!==h[a])var c=String(h[a]),b=""===b?c:b+("0000000".slice(0,7-c.length)+c);return b}function c(a,b,e){return 0===b?e:1===b%2?c(a,b-1,e*a):c(a*a,b/2,e)}var d,g,h;d=1E7;g=6;h=[0,0,0,0,0,0];Number.prototype.toFixed=function(d){var f,g,k;d=Number(d);d=d!==d?0:Math.floor(d);if(0>d||20<d)throw new RangeError("Number.toFixed called with invalid number of decimals");f=Number(this);if(f!==f)return"NaN";if(-1E21>=
f||1E21<=f)return String(f);g="";0>f&&(g="-",f=-f);k="0";if(1E-21<f){k=f*c(2,69,1);for(var h=0;4096<=k;)h+=12,k/=4096;for(;2<=k;)h+=1,k/=2;k=h-69;f=0>k?f*c(2,-k,1):f/c(2,k,1);f*=4503599627370496;k=52-k;if(0<k){a(0,f);for(f=d;7<=f;)a(1E7,0),f-=7;a(c(10,f,1),0);for(f=k-1;23<=f;)b(8388608),f-=23;b(1<<f);a(1,1);b(2);k=e()}else a(0,f),a(1<<-k,0),k=e()+"0.00000000000000000000".slice(2,2+d)}0<d?(f=k.length,k=f<=d?g+"0.0000000000000000000".slice(0,d-f+2)+k:g+k.slice(0,f-d)+"."+k.slice(f-d)):k=g+k;return k}}();
var D=String.prototype.split;2!=="ab".split(/(?:ab)*/).length||4!==".".split(/(.?)(.?)/).length||"t"==="tesst".split(/(s)*/)[1]||"".split(/.?/).length||1<".".split(/()()/).length?function(){var a=void 0===/()??/.exec("")[1];String.prototype.split=function(b,e){var c=this;if(void 0===b&&0===e)return[];if("[object RegExp]"!==Object.prototype.toString.call(b))return D.apply(this,arguments);var d=[],g=(b.ignoreCase?"i":"")+(b.multiline?"m":"")+(b.a?"x":"")+(b.b?"y":""),h=0;b=RegExp(b.source,g+"g");var l,
f,m,c=c+"";a||(l=RegExp("^"+b.source+"$(?!\\s)",g));for(e=void 0===e?4294967295:e>>>0;f=b.exec(c);){g=f.index+f[0].length;if(g>h&&(d.push(c.slice(h,f.index)),!a&&1<f.length&&f[0].replace(l,function(){for(var a=1;a<arguments.length-2;a++)void 0===arguments[a]&&(f[a]=void 0)}),1<f.length&&f.index<c.length&&Array.prototype.push.apply(d,f.slice(1)),m=f[0].length,h=g,d.length>=e))break;b.lastIndex===f.index&&b.lastIndex++}h===c.length?!m&&b.test("")||d.push(""):d.push(c.slice(h));return d.length>e?d.slice(0,
e):d}}():"0".split(void 0,0).length&&(String.prototype.split=function(a,b){return void 0===a&&0===b?[]:D.apply(this,arguments)});if("".substr&&"b"!=="0b".substr(-1)){var H=String.prototype.substr;String.prototype.substr=function(a,b){return H.call(this,0>a?0>(a=this.length+a)?0:a:a,b)}}n="\t\n\x0B\f\r \u00a0\u1680\u180e\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u202f\u205f\u3000\u2028\u2029\ufeff";if(!String.prototype.trim||n.trim()){n="["+n+"]";var I=RegExp("^"+n+n+"*"),J=
RegExp(n+n+"*$");String.prototype.trim=function(){if(void 0===this||null===this)throw new TypeError("can't convert "+this+" to object");return String(this).replace(I,"").replace(J,"")}}if(8!==parseInt(n+"08")||22!==parseInt(n+"0x16"))parseInt=function(a){var b=/^0[xX]/;return function(e,c){e=String(e).trim();+c||(c=b.test(e)?16:10);return a(e,c)}}(parseInt)})();
