// ES6-shim 0.10.1 (c) 2013-2014 Paul Miller (http://paulmillr.com)
// ES6-shim may be freely distributed under the MIT license.
// For more details and documentation:
// https://github.com/paulmillr/es6-shim/
// Fixed for usage in Notepad++, may work incorrectly because jN uses shitty IE 7 engine

(function(g){var z=function(g){try{g()}catch(q){return!1}return!0},F=function(g,q){try{var m=function(){g.apply(this,arguments)};if(!m.__proto__)return!1;Object.setPrototypeOf(m,g);m.prototype=Object.create(g.prototype,{constructor:{value:g}});return q(m)}catch(z){return!1}},I=function(){var g=!1;if(String.prototype.startsWith)try{"/a/".startsWith(/a/)}catch(q){g=!0}return g},E=function(){var v="undefined"===typeof global?this:global,q=isFinite,m;if(m=!!Object.defineProperty)try{Object.defineProperty({},
"x",{}),m=!0}catch(E){m=!1}var A=m;m=I();var G=Array.prototype.slice,J=String.prototype.indexOf,t=Object.prototype.toString,K=Object.prototype.hasOwnProperty,l=function(a,b){Object.keys(b).forEach(function(c){var d=b[c];if(!(c in a))try{if(A)Object.defineProperty(a,c,{configurable:!0,enumerable:!1,writable:!0,value:d});else try{a[c]=d}catch(f){eval(c+"=d")}}catch(h){}})},w="object"===typeof Symbol&&Symbol.iterator||"_es6shim_iterator_";"function"==typeof Set&&"function"===typeof(new Set)["@@iterator"]&&
(w="@@iterator");var p=function(a,b){b||(b=function(){return this});var c={};c[w]=b;l(a,c)},H=function(a){var b=t.call(a),c="[object Arguments]"===b;c||(c="[object Array]"!==b&&null!==a&&"object"===typeof a&&"number"===typeof a.length&&0<=a.length&&"[object Function]"===t.call(a.callee));return c},B=function(a){if(!e.TypeIsObject(a))throw new TypeError("bad object");a._es6construct||(a.constructor&&e.IsCallable(a.constructor["@@create"])&&(a=a.constructor["@@create"](a)),l(a,{_es6construct:!0}));
return a},e={CheckObjectCoercible:function(a,b){if(null==a)throw new TypeError(b||"Cannot call method on "+a);return a},TypeIsObject:function(a){return null!=a&&Object(a)===a},ToObject:function(a,b){return Object(e.CheckObjectCoercible(a,b))},IsCallable:function(a){return"function"===typeof a&&"[object Function]"===t.call(a)},ToInt32:function(a){return a>>0},ToUint32:function(a){return a>>>0},ToInteger:function(a){a=+a;return Number.isNaN(a)?0:0!==a&&Number.isFinite(a)?Math.sign(a)*Math.floor(Math.abs(a)):
a},ToLength:function(a){a=e.ToInteger(a);return 0>=a?0:a>Number.MAX_SAFE_INTEGER?Number.MAX_SAFE_INTEGER:a},SameValue:function(a,b){return a===b?0===a?1/a===1/b:!0:Number.isNaN(a)&&Number.isNaN(b)},SameValueZero:function(a,b){return a===b||Number.isNaN(a)&&Number.isNaN(b)},IsIterable:function(a){return e.TypeIsObject(a)&&(a[w]!==g||H(a))},GetIterator:function(a){if(H(a))return new ArrayIterator(a,"value");a=a[w]();if(!e.TypeIsObject(a))throw new TypeError("bad iterator");return a},IteratorNext:function(a){var b=
1<arguments.length?a.next(arguments[1]):a.next();if(!e.TypeIsObject(b))throw new TypeError("bad iterator");return b},Construct:function(a,b){var c;c=e.IsCallable(a["@@create"])?a["@@create"]():Object.create(a.prototype||null);l(c,{_es6construct:!0});var d=a.apply(c,b);return e.TypeIsObject(d)?d:c}},L=function(){function a(a){var c=Math.floor(a);a-=c;return 0.5>a?c:0.5<a?c+1:c%2?c+1:c}var b={toFloat32:function(c){var b=c,h,k,e;b!==b?(h=255,k=Math.pow(2,22),c=0):Infinity===b||-Infinity===b?(h=255,k=
0,c=0>b?1:0):0===b?(k=h=0,c=-Infinity===1/b?1:0):(c=0>b,b=Math.abs(b),b>=Math.pow(2,-126)?(h=Math.min(Math.floor(Math.log(b)/Math.LN2),1023),k=a(b/Math.pow(2,h)*Math.pow(2,23)),2<=k/Math.pow(2,23)&&(h+=1,k=1),127<h?(h=255,k=0):(h+=127,k-=Math.pow(2,23))):(h=0,k=a(b/Math.pow(2,-149))));e=[];for(b=23;b;b-=1)e.push(k%2?1:0),k=Math.floor(k/2);for(b=8;b;b-=1)e.push(h%2?1:0),h=Math.floor(h/2);e.push(c?1:0);e.reverse();h=e.join("");for(c=[];h.length;)c.push(parseInt(h.substring(0,8),2)),h=h.substring(8);
h=[];for(k=c.length;k;k-=1)for(e=c[k-1],b=8;b;b-=1)h.push(e%2?1:0),e>>=1;h.reverse();k=h.join("");c=parseInt(k.substring(0,1),2)?-1:1;h=parseInt(k.substring(1,9),2);k=parseInt(k.substring(9),2);return 255===h?0!==k?NaN:Infinity*c:0<h?c*Math.pow(2,h-127)*(1+k/Math.pow(2,23)):0!==k?c*Math.pow(2,-126)*(k/Math.pow(2,23)):0>c?-0:0}};if("undefined"!==typeof Float32Array){var c=new Float32Array(1);b.toFloat32=function(a){c[0]=a;return c[0]}}return b}();l(String,{fromCodePoint:function(){for(var a=G.call(arguments,
0,arguments.length),b=[],c,d=0,f=a.length;d<f;d++){c=Number(a[d]);if(!e.SameValue(c,e.ToInteger(c))||0>c||1114111<c)throw new RangeError("Invalid code point "+c);65536>c?b.push(String.fromCharCode(c)):(c-=65536,b.push(String.fromCharCode((c>>10)+55296)),b.push(String.fromCharCode(c%1024+56320)))}return b.join("")},raw:function(a){var b=G.call(arguments,1,arguments.length),c=e.ToObject(a,"bad callSite").raw,c=e.ToObject(c,"bad raw value"),d=Object.keys(c).length,d=e.ToLength(d);if(0===d)return"";for(var f=
[],h=0,k,n;h<d;){k=String(h);n=c[k];n=String(n);f.push(n);if(h+1>=d)break;n=b[k];if(n===g)break;k=String(n);f.push(k);h++}return f.join("")}});var C={repeat:function(){var a=function(b,c){if(1>c)return"";if(c%2)return a(b,c-1)+b;var d=a(b,c/2);return d+d};return function(b){var c=String(e.CheckObjectCoercible(this));b=e.ToInteger(b);if(0>b||Infinity===b)throw new RangeError("Invalid String#repeat value");return a(c,b)}}(),startsWith:function(a){var b=String(e.CheckObjectCoercible(this));if("[object RegExp]"===
t.call(a))throw new TypeError('Cannot call method "startsWith" with a regex');a=String(a);var c=Math.max(e.ToInteger(1<arguments.length?arguments[1]:g),0);return b.slice(c,c+a.length)===a},endsWith:function(a){var b=String(e.CheckObjectCoercible(this));if("[object RegExp]"===t.call(a))throw new TypeError('Cannot call method "endsWith" with a regex');a=String(a);var c=b.length,d=1<arguments.length?arguments[1]:g,d=d===g?c:e.ToInteger(d),c=Math.min(Math.max(d,0),c);return b.slice(c-a.length,c)===a},
contains:function(a){return-1!==J.call(this,a,1<arguments.length?arguments[1]:g)},codePointAt:function(a){var b=String(e.CheckObjectCoercible(this)),c=e.ToInteger(a),d=b.length;if(0>c||c>=d)return g;a=b.charCodeAt(c);if(55296>a||56319<a||c+1===d)return a;b=b.charCodeAt(c+1);return 56320>b||57343<b?a:1024*(a-55296)+(b-56320)+65536}};l(String.prototype,C);var D=function(a){this._s=String(e.CheckObjectCoercible(a));this._i=0};D.prototype.next=function(){var a=this._s,b=this._i;if(a===g||b>=a.length)return this._s=
g,{value:g,done:!0};var c=a.charCodeAt(b);55296>c||56319<c||b+1==a.length?c=1:(c=a.charCodeAt(b+1),c=56320>c||57343<c?1:2);this._i=b+c;return{value:a.substr(b,c),done:!1}};p(D.prototype);p(String.prototype,function(){return new D(this)});m||(String.prototype.startsWith=C.startsWith,String.prototype.endsWith=C.endsWith);l(Array,{from:function(a){var b=1<arguments.length?arguments[1]:g,c=2<arguments.length?arguments[2]:g,d=e.ToObject(a,"bad iterable");if(b!==g&&!e.IsCallable(b))throw new TypeError("Array.from: when provided, the second argument must be a function");
for(var f=e.IsIterable(d),h=f?0:e.ToLength(d.length),k=e.IsCallable(this)?Object(f?new this:new this(h)):Array(h),n=f?e.GetIterator(d):null,r,u=0;f||u<h;u++){if(f){r=e.IteratorNext(n);if(r.done){h=u;break}r=r.value}else r=d[u];k[u]=b!==g?c?b.call(c,r):b(r):r}k.length=h;return k},of:function(){return Array.from(arguments)}});l(v,{ArrayIterator:function(a,b){this.i=0;this.array=a;this.kind=b}});l(ArrayIterator.prototype,{next:function(){var a=this.i,b=this.array;if(a===g||this.kind===g)throw new TypeError("Not an ArrayIterator");
if(b!==g)for(var c=e.ToLength(b.length);a<c;){var c=this.kind,d;"key"===c&&(d=a);"value"===c&&(d=b[a]);"entry"===c&&(d=[a,b[a]]);this.i=a+1;return{value:d,done:!1}}this.array=g;return{value:g,done:!0}}});p(ArrayIterator.prototype);l(Array.prototype,{copyWithin:function(a,b,c){var d=c;c=e.ToObject(this);var f=e.ToLength(c.length);a=e.ToInteger(a);b=e.ToInteger(b);a=0>a?Math.max(f+a,0):Math.min(a,f);b=0>b?Math.max(f+b,0):Math.min(b,f);d=d===g?f:e.ToInteger(d);d=0>d?Math.max(f+d,0):Math.min(d,f);f=Math.min(d-
b,f-a);d=1;for(b<a&&a<b+f&&(d=-1,b+=f-1,a+=f-1);0<f;)K.call(c,b)?c[a]=c[b]:delete c[b],b+=d,a+=d,f-=1;return c},fill:function(a,b,c){var d=e.ToObject(this),f=e.ToLength(d.length);b=e.ToInteger(b===g?0:b);c=e.ToInteger(c===g?f:c);for(b=0>b?Math.max(f+b,0):Math.min(b,f);b<f&&b<c;++b)d[b]=a;return d},find:function(a,b){var c=e.ToObject(this),d=e.ToLength(c.length);if(!e.IsCallable(a))throw new TypeError("Array#find: predicate must be a function");for(var f=0,h;f<d;f++)if(f in c&&(h=c[f],a.call(b,h,f,
c)))return h;return g},findIndex:function(a,b){var c=e.ToObject(this),d=e.ToLength(c.length);if(!e.IsCallable(a))throw new TypeError("Array#findIndex: predicate must be a function");for(var f=0;f<d;f++)if(f in c&&a.call(b,c[f],f,c))return f;return-1},keys:function(){return new ArrayIterator(this,"key")},values:function(){return new ArrayIterator(this,"value")},entries:function(){return new ArrayIterator(this,"entry")}});p(Array.prototype,function(){return this.values()});Object.getPrototypeOf&&p(Object.getPrototypeOf([].values()));
m=Math.pow(2,53)-1;l(Number,{MAX_SAFE_INTEGER:m,MIN_SAFE_INTEGER:-m,EPSILON:2.220446049250313E-16,parseInt:parseInt,parseFloat:parseFloat,isFinite:function(a){return"number"===typeof a&&q(a)},isInteger:function(a){return"number"===typeof a&&!Number.isNaN(a)&&Number.isFinite(a)&&e.ToInteger(a)===a},isSafeInteger:function(a){return Number.isInteger(a)&&Math.abs(a)<=Number.MAX_SAFE_INTEGER},isNaN:function(a){return a!==a}});l(Number.prototype,{});A&&(l(Object,{getOwnPropertyDescriptors:function(a){var b=
{};Object.getOwnPropertyNames(a).forEach(function(c){b[c]=Object.getOwnPropertyDescriptor(a,c)});return b},getPropertyDescriptor:function(a,b){for(var c=Object.getOwnPropertyDescriptor(a,b),d=Object.getPrototypeOf(a);c===g&&null!==d;)c=Object.getOwnPropertyDescriptor(d,b),d=Object.getPrototypeOf(d);return c},getPropertyNames:function(a){var b=Object.getOwnPropertyNames(a);a=Object.getPrototypeOf(a);for(var c=function(a){-1===b.indexOf(a)&&b.push(a)};null!==a;)Object.getOwnPropertyNames(a).forEach(c),
a=Object.getPrototypeOf(a);return b},assign:function(a,b){return Object.keys(b).reduce(function(a,d){a[d]=b[d];return a},a)}}),l(Object,{setPrototypeOf:function(a,b){var c,d=function(a,b){if(!e.TypeIsObject(a))throw new TypeError("cannot set prototype on a non-object");if(null!==b&&!e.TypeIsObject(b))throw new TypeError("can only set prototype to an object or null"+b);c.call(a,b);return a};try{c=a.getOwnPropertyDescriptor(a.prototype,b).set,c.call({},null)}catch(f){if(a.prototype!=={}[b])return;c=
function(a){this[b]=a};d.polyfill=d(d({},null),a.prototype)instanceof a}return d}(Object,"__proto__")}));Object.setPrototypeOf&&Object.getPrototypeOf&&null!==Object.getPrototypeOf(Object.setPrototypeOf({},null))&&null===Object.getPrototypeOf(Object.create(null))&&function(){var a=Object.create(null),b=Object.getPrototypeOf,c=Object.setPrototypeOf;Object.getPrototypeOf=function(c){c=b(c);return c===a?null:c};Object.setPrototypeOf=function(b,e){null===e&&(e=a);return c(b,e)};Object.setPrototypeOf.polyfill=
!1}();l(Object,{getOwnPropertyKeys:function(a){return Object.keys(a)},is:function(a,b){return e.SameValue(a,b)}});try{Object.keys("foo")}catch(N){var M=Object.keys;Object.keys=function(a){return M(e.ToObject(a))}}m={acosh:function(a){a=Number(a);return Number.isNaN(a)||1>a?NaN:1===a?0:Infinity===a?a:Math.log(a+Math.sqrt(a*a-1))},asinh:function(a){a=Number(a);return 0!==a&&q(a)?0>a?-Math.asinh(-a):Math.log(a+Math.sqrt(a*a+1)):a},atanh:function(a){a=Number(a);return Number.isNaN(a)||-1>a||1<a?NaN:-1===
a?-Infinity:1===a?Infinity:0===a?a:0.5*Math.log((1+a)/(1-a))},cbrt:function(a){a=Number(a);if(0===a)return a;var b=0>a;b&&(a=-a);a=Math.pow(a,1/3);return b?-a:a},clz32:function(a){a=Number(a);if(Number.isNaN(a))return NaN;a=e.ToUint32(a);return 0===a?32:32-a.toString(2).length},cosh:function(a){a=Number(a);if(0===a)return 1;if(Number.isNaN(a))return NaN;if(!q(a))return Infinity;0>a&&(a=-a);return 21<a?Math.exp(a)/2:(Math.exp(a)+Math.exp(-a))/2},expm1:function(a){a=Number(a);if(-Infinity===a)return-1;
if(!q(a)||0===a)return a;for(var b=0,c=1;50>c;c++){for(var d=2,e=1;d<=c;d++)e*=d;b+=Math.pow(a,c)/e}return b},hypot:function(a,b){var c=!1,d=!0,e=!1,h=[];Array.prototype.every.call(arguments,function(a){a=Number(a);Number.isNaN(a)?c=!0:Infinity===a||-Infinity===a?e=!0:0!==a&&(d=!1);if(e)return!1;c||h.push(Math.abs(a));return!0});if(e)return Infinity;if(c)return NaN;if(d)return 0;h.sort(function(a,b){return b-a});var k=h[0],n=h.map(function(a){return a/deploy/jN/k}).reduce(function(a,b){return a+b*b},0);return k*
Math.sqrt(n)},log2:function(a){return Math.log(a)*Math.LOG2E},log10:function(a){return Math.log(a)*Math.LOG10E},log1p:function(a){a=Number(a);if(-1>a||Number.isNaN(a))return NaN;if(0===a||Infinity===a)return a;if(-1===a)return-Infinity;var b=0;if(0>a||1<a)return Math.log(1+a);for(var c=1;50>c;c++)b=0===c%2?b-Math.pow(a,c)/c:b+Math.pow(a,c)/c;return b},sign:function(a){a=+a;return 0===a||Number.isNaN(a)?a:0>a?-1:1},sinh:function(a){a=Number(a);return q(a)&&0!==a?(Math.exp(a)-Math.exp(-a))/2:a},tanh:function(a){a=
Number(a);return Number.isNaN(a)||0===a?a:Infinity===a?1:-Infinity===a?-1:(Math.exp(a)-Math.exp(-a))/(Math.exp(a)+Math.exp(-a))},trunc:function(a){a=Number(a);return 0>a?-Math.floor(-a):Math.floor(a)},imul:function(a,b){var c=a&65535,d=b&65535;return c*d+((a>>>16&65535)*d+c*(b>>>16&65535)<<16>>>0)|0},fround:function(a){return 0===a||Infinity===a||-Infinity===a||Number.isNaN(a)?a:L.toFloat32(Number(a))}};l(Math,m);-5!==Math.imul(4294967295,5)&&(Math.imul=m.imul);m=function(){var a,b;e.IsPromise=function(a){return e.TypeIsObject(a)&&
a._promiseConstructor&&a._status!==g?!0:!1};var c=function(a){if(!e.IsCallable(a))throw new TypeError("bad promise constructor");var b=this;b.promise=e.Construct(a,[function(a,c){b.resolve=a;b.reject=c}]);if(!b.promise._es6construct)throw new TypeError("bad promise constructor");if(!e.IsCallable(b.resolve)||!e.IsCallable(b.reject))throw new TypeError("bad promise constructor");};a=function(){var a=[];window.addEventListener("message",function(b){b.source==window&&"zero-timeout-message"==b.data&&(b.stopPropagation(),
0!==a.length&&a.shift()())},!0);return function(b){a.push(b);window.postMessage("zero-timeout-message","*")}};a=function(){var a=this.Promise;return a&&a.resolve&&function(b){return a.resolve().then(b)}};var d;d="function"==typeof setImmediate&&e.IsCallable(setImmediate)?setImmediate.bind(v):"object"===typeof process&&process.nextTick?process.nextTick:a()||function(a){setTimeout(a,0)};var f=function(a,b){a.forEach(function(a){d(function(){var c=a.handler,d=a.capability,e=d.resolve,k=d.reject;try{var f=
c(b);if(f===d.promise)throw new TypeError("self resolution");h(f,d)||e(f)}catch(r){k(r)}})})},h=function(a,b){if(!e.TypeIsObject(a))return!1;var c=b.resolve,d=b.reject;try{var h=a.then;if(!e.IsCallable(h))return!1;h.call(a,c,d)}catch(k){d(k)}return!0},k=function(a,b,d){return function(e){if(e===a)return d(new TypeError("self resolution"));var k=new c(a._promiseConstructor);return h(e,k)?k.promise.then(b,d):b(e)}};a=function(a){var b=this,b=B(b);if(!b._promiseConstructor)throw new TypeError("bad promise");
if(b._status!==g)throw new TypeError("promise already initialized");if(!e.IsCallable(a))throw new TypeError("not a valid resolver");b._status="unresolved";b._resolveReactions=[];b._rejectReactions=[];var c=function(a){if("unresolved"===b._status){var c=b._resolveReactions;b._result=a;b._resolveReactions=g;b._rejectReactions=g;b._status="has-resolution";f(c,a)}},d=function(a){if("unresolved"===b._status){var c=b._rejectReactions;b._result=a;b._resolveReactions=g;b._rejectReactions=g;b._status="has-rejection";
f(c,a)}};try{a(c,d)}catch(h){d(h)}return b};b=a.prototype;l(a,{"@@create":function(a){var c=this.prototype||b;a=a||Object.create(c);l(a,{_status:g,_result:g,_resolveReactions:g,_rejectReactions:g,_promiseConstructor:g});a._promiseConstructor=this;return a}});var n=function(a,b,c,d){var h=!1;return function(e){h||(h=!0,b[a]=e,0===--d.count&&(e=c.resolve,e(b)))}};a.all=function(a){var b=new c(this),d=b.resolve,h=b.reject;try{if(!e.IsIterable(a))throw new TypeError("bad iterable");var k=e.GetIterator(a);
a=[];for(var f={count:1},g=0;;g++){var l=e.IteratorNext(k);if(l.done)break;var m=this.resolve(l.value),p=n(g,a,b,f);f.count++;m.then(p,b.reject)}0===--f.count&&d(a)}catch(q){h(q)}return b.promise};a.race=function(a){var b=new c(this),d=b.resolve,h=b.reject;try{if(!e.IsIterable(a))throw new TypeError("bad iterable");for(var k=e.GetIterator(a);;){var f=e.IteratorNext(k);if(f.done)break;this.resolve(f.value).then(d,h)}}catch(g){h(g)}return b.promise};a.reject=function(a){var b=new c(this),d=b.reject;
d(a);return b.promise};a.resolve=function(a){if(e.IsPromise(a)&&a._promiseConstructor===this)return a;var b=new c(this),d=b.resolve;d(a);return b.promise};a.prototype["catch"]=function(a){return this.then(g,a)};a.prototype.then=function(a,b){if(!e.IsPromise(this))throw new TypeError("not a promise");var d=new c(this.constructor);e.IsCallable(b)||(b=function(a){throw a;});e.IsCallable(a)||(a=function(a){return a});var h=k(this,a,b),h={capability:d,handler:h},g={capability:d,handler:b};switch(this._status){case "unresolved":this._resolveReactions.push(h);
this._rejectReactions.push(g);break;case "has-resolution":f([h],this._result);break;case "has-rejection":f([g],this._result);break;default:throw new TypeError("unexpected");}return d.promise};return a}();l(v,{Promise:m});F(this.Promise,function(a){return a.resolve(42)instanceof a})||(Promise=m);if(A){var s=function(a){var b=typeof a;return"string"===b?"$"+a:"number"===b?a:null},x=function(){return Object.create?Object.create(null):{}},y={Map:function(){function a(a,b){this.key=a;this.value=b;this.prev=
this.next=null}function b(a,b){this.i=this.head=a._head;this.kind=b}function c(b){var c;c=B(this);if(!c._es6map)throw new TypeError("bad map");var d=new a(null,null);d.next=d.prev=d;l(c,{_head:d,_storage:x(),_size:0});if(b!==g&&null!==b){b=e.GetIterator(b);d=c.set;if(!e.IsCallable(d))throw new TypeError("bad map");for(;;){var f=e.IteratorNext(b);if(f.done)break;f=f.value;if(!e.TypeIsObject(f))throw new TypeError("expected iterable of pairs");d.call(c,f[0],f[1])}}return c}var d={};a.prototype.isRemoved=
function(){return this.key===d};b.prototype={next:function(){var a=this.i,b=this.kind,c=this.head;if(this.i===g)return{value:g,done:!0};for(;a.isRemoved()&&a!==c;)a=a.prev;for(;a.next!==c;)if(a=a.next,!a.isRemoved())return b="key"===b?a.key:"value"===b?a.value:[a.key,a.value],this.i=a,{value:b,done:!1};this.i=g;return{value:g,done:!0}}};p(b.prototype);var f=c.prototype;l(c,{"@@create":function(a){var b=this.prototype||f;a=a||Object.create(b);l(a,{_es6map:!0});return a}});Object.defineProperty(c.prototype,
"size",{configurable:!0,enumerable:!1,get:function(){if("undefined"===typeof this._size)throw new TypeError("size method called on incompatible Map");return this._size}});l(c.prototype,{get:function(a){var b=s(a);if(null!==b)return(a=this._storage[b])?a.value:g;for(var c=b=this._head;(c=c.next)!==b;)if(e.SameValueZero(c.key,a))return c.value;return g},has:function(a){var b=s(a);if(null!==b)return"undefined"!==typeof this._storage[b];for(var c=b=this._head;(c=c.next)!==b;)if(e.SameValueZero(c.key,
a))return!0;return!1},set:function(b,c){var d=this._head,f=d,g,l=s(b);if(null!==l){if("undefined"!==typeof this._storage[l]){this._storage[l].value=c;return}g=this._storage[l]=new a(b,c);f=d.prev}for(;(f=f.next)!==d;)if(e.SameValueZero(f.key,b)){f.value=c;return}g=g||new a(b,c);e.SameValue(-0,b)&&(g.key=0);g.next=this._head;g.prev=this._head.prev;g.prev.next=g;g.next.prev=g;this._size+=1},"delete":function(a){var b=this._head,c=b,f=s(a);if(null!==f){if("undefined"===typeof this._storage[f])return!1;
c=this._storage[f].prev;delete this._storage[f]}for(;(c=c.next)!==b;)if(e.SameValueZero(c.key,a))return c.key=c.value=d,c.prev.next=c.next,c.next.prev=c.prev,this._size-=1,!0;return!1},clear:function(){this._size=0;this._storage=x();for(var a=this._head,b,c=a.next;(b=c)!==a;)b.key=b.value=d,c=b.next,b.next=b.prev=a;a.next=a.prev=a},keys:function(){return new b(this,"key")},values:function(){return new b(this,"value")},entries:function(){return new b(this,"key+value")},forEach:function(a){for(var b=
1<arguments.length?arguments[1]:null,c=this.entries(),d=c.next();!d.done;d=c.next())a.call(b,d.value[1],d.value[0],this)}});p(c.prototype,function(){return this.entries()});return c}(),Set:function(){var a=function(a){var b;b=B(this);if(!b._es6set)throw new TypeError("bad set");l(b,{"[[SetData]]":null,_storage:x()});if(a!==g&&null!==a){a=e.GetIterator(a);var c=b.add;if(!e.IsCallable(c))throw new TypeError("bad set");for(;;){var k=e.IteratorNext(a);if(k.done)break;c.call(b,k.value)}}return b},b=a.prototype;
l(a,{"@@create":function(a){var c=this.prototype||b;a=a||Object.create(c);l(a,{_es6set:!0});return a}});var c=function(a){if(!a["[[SetData]]"]){var b=a["[[SetData]]"]=new y.Map;Object.keys(a._storage).forEach(function(a){a=36===a.charCodeAt(0)?a.substring(1):+a;b.set(a,a)});a._storage=null}};Object.defineProperty(a.prototype,"size",{configurable:!0,enumerable:!1,get:function(){if("undefined"===typeof this._storage)throw new TypeError("size method called on incompatible Set");c(this);return this["[[SetData]]"].size}});
l(a.prototype,{has:function(a){var b;if(this._storage&&null!==(b=s(a)))return!!this._storage[b];c(this);return this["[[SetData]]"].has(a)},add:function(a){var b;if(this._storage&&null!==(b=s(a)))this._storage[b]=!0;else return c(this),this["[[SetData]]"].set(a,a)},"delete":function(a){var b;if(this._storage&&null!==(b=s(a)))delete this._storage[b];else return c(this),this["[[SetData]]"]["delete"](a)},clear:function(){if(this._storage)this._storage=x();else return this["[[SetData]]"].clear()},keys:function(){c(this);
return this["[[SetData]]"].keys()},values:function(){c(this);return this["[[SetData]]"].values()},entries:function(){c(this);return this["[[SetData]]"].entries()},forEach:function(a){var b=1<arguments.length?arguments[1]:null,e=this;c(this);this["[[SetData]]"].forEach(function(c,g){a.call(b,g,g,e)})}});p(a.prototype,function(){return this.values()});return a}()};l(v,y);if(Map||Set)if("function"!==typeof Map.prototype.clear||0!==(new Set).size||0!==(new Map).size||"function"!==typeof Set.prototype.keys||
"function"!==typeof Map.prototype.forEach||"function"!==typeof Set.prototype.forEach||z(Map)||z(Set)||!F(Map,function(a){return new a([])instanceof a}))Map=y.Map,Set=y.Set;p(Object.getPrototypeOf((new Map).keys()));p(Object.getPrototypeOf((new Set).keys()))}};"function"===typeof define&&"object"===typeof define.amd&&define.amd?define(E):E()})();
